### ISSUE TITLE
Incorrect image for Southwest Airlines (SWA) 

### ISSUE THREAD

**Issue by Jstinii** [theyetty/vatskyterminal#24]
Great work on this project, very immersive. The logo for SWA is currently https://images.kiwi.com/airlines/64x64/WN.png when it should look like this https://logos-world.net/wp-content/uploads/2020/10/Southwest-Airlines-Emblem.png, thank you

**Comment by theyetty** [comment]
@Jstinii there's not a lot I can do about it as Southwest are suing Kiwi, if I put a Southwest logo in place of it they may come after me!

https://www.travelweekly.com/Travel-News/Airline-News/Facing-lawsuit-OTA-pulls-Southwest-logo-but-keeps-selling-its-tickets

**Comment by Jstinii** [comment]
Completely understandable, better safe than sorry.
